//auth
export const REGISTER_REQUEST: 'REGISTER_REQUEST' = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS';
export const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED';

export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const LOGIN_FAILED: 'LOGIN_FAILED' = 'LOGIN_FAILED';

export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED';

export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS'
export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED'

export const USER_SET: 'USER_SET' = 'USER_SET'

export const USER_PATCH_REQUEST: 'USER_PATCH_REQUEST' = 'USER_PATCH_REQUEST'
export const USER_PATCH_SUCCESS: 'USER_PATCH_SUCCESS' = 'USER_PATCH_SUCCESS'
export const USER_PATCH_FAILED: 'USER_PATCH_FAILED' = 'USER_PATCH_FAILED'

export const USER_UPDATE: 'USER_UPDATE' = 'USER_UPDATE'

export const AUTH_CHECKED: 'AUTH_CHECKED' = 'AUTH_CHECKED'

//burger-constructor
export const ADD_CONSTRUCTOR_ITEM: 'ADD_CONSTRUCTOR_ITEM' = 'ADD_CONSTRUCTOR_ITEM';
export const REMOVE_CONSTRUCTOR_ITEM: 'REMOVE_CONSTRUCTOR_ITEM' = 'REMOVE_CONSTRUCTOR_ITEM';
export const MOVE_CONSTRUCTOR_ITEM: 'MOVE_CONSTRUCTOR_ITEM' = 'MOVE_CONSTRUCTOR_ITEM';
export const RESET_CONSTRUCTOR_ITEMS: 'RESET_CONSTRUCTOR_ITEMS' = 'RESET_CONSTRUCTOR_ITEMS';

//ingredient-detail
export const INGREDIENT_DETAIL_SET: 'INGREDIENT_DETAIL_SET_DATA' = 'INGREDIENT_DETAIL_SET_DATA';
export const SET_BROWSED_CATEGORY: 'SET_BROWSED_CATEGORY' = 'SET_BROWSED_CATEGORY';

//ingredients
export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED';

//order
export const MAKE_ORDER_REQUEST: 'MAKE_ORDER_REQUEST' = 'MAKE_ORDER_REQUEST';
export const MAKE_ORDER_SUCCESS: 'MAKE_ORDER_SUCCESS' = 'MAKE_ORDER_SUCCESS';
export const MAKE_ORDER_FAILED: 'MAKE_ORDER_FAILED' = 'MAKE_ORDER_FAILED';

//reset-password
export const RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST' = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED' = 'RESET_PASSWORD_FAILED';

export const FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST' = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS' = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED: 'FORGOT_PASSWORD_FAILED' = 'FORGOT_PASSWORD_FAILED';
